# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

url: 'index.md'
menu:
- {name: 'About', url: 'about'}
- {name: 'Projects', url: 'projects'}
- {name: 'Learning Resources', url: 'resources'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
social:
- {icon: 'github', link: 'https://github.com/ankitmathanker'}
- {icon: 'google', link: 'https://scholar.google.com/citations?user=1PwEl2AAAAAJ&hl=en'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/ankit-mathanker/'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
