#!/usr/bin/env python3
"""
Generate GitHub profile README.md from ../profile.yaml (repo root).
Stable output: fixed section order, trailing newline, UTF-8.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import yaml


def load_profile(repo_root: Path) -> dict:
    path = repo_root / "profile.yaml"
    with path.open(encoding="utf-8") as f:
        return yaml.safe_load(f)


def md_paragraph(text: str) -> str:
    return text.strip()


def render(data: dict) -> str:
    lines: list[str] = []
    lines.append("<!-- Generated by scripts/generate_profile_readme.py from profile.yaml — do not edit on github.com -->")
    lines.append("")

    name = data["name"]
    title = data["title"]
    affiliation = data["affiliation"]
    tagline = data["tagline"]

    img = data.get("profile_image_url") or ""
    if img:
        lines.append(f'<img src="{img}" alt="{name}" width="240" />')
        lines.append("")

    lines.append(f"# Hi, I'm {name}")
    lines.append("")
    lines.append(f"**{title}** · {affiliation}")
    lines.append("")
    lines.append(f"*{tagline}*")
    lines.append("")

    site = data.get("site", {}) or {}
    base = site.get("base_url", "https://ankitmathanker.github.io").rstrip("/")
    links = data.get("links", {}) or {}

    lines.append("## About")
    lines.append("")
    lines.append(md_paragraph(data.get("about_lead", "")))
    lines.append("")
    for p in data.get("about_paragraphs") or []:
        lines.append(md_paragraph(str(p)))
        lines.append("")

    lines.append("## Research")
    lines.append("")
    lines.append(md_paragraph(data.get("research_lead", "")))
    lines.append("")
    for area in data.get("research_areas") or []:
        t = area.get("title", "")
        d = area.get("description", "")
        tags = area.get("tags") or []
        lines.append(f"### {t}")
        lines.append("")
        lines.append(md_paragraph(d))
        if tags:
            lines.append("")
            lines.append(" ".join(f"`{t}`" for t in tags))
        lines.append("")

    lines.append("## Snapshot")
    lines.append("")
    stats = data.get("stats") or {}
    lines.append(
        f"- **Publications:** {stats.get('publications', '')} · "
        f"[See full list on my site]({base}/#publications)"
    )
    lines.append(f"- **Countries:** {stats.get('countries', '')}")
    lines.append(f"- **Awards:** {stats.get('awards', '')}")
    lines.append("")

    lines.append("## Education")
    lines.append("")
    for row in data.get("education") or []:
        deg = row.get("degree", "")
        meta = row.get("meta", "")
        lines.append(f"- **{deg}** — {meta}")
    lines.append("")

    lines.append("## Connect")
    lines.append("")
    lines.append(md_paragraph(data.get("contact_lead", "")))
    lines.append("")
    if links.get("website"):
        lines.append(f"- **Website:** [{links['website']}]({links['website']})")
    if links.get("email"):
        em = links["email"]
        lines.append(f"- **Email:** [{em}](mailto:{em})")
    if links.get("cv"):
        lines.append(f"- **CV (PDF):** [Download]({links['cv']})")
    if links.get("scholar"):
        lines.append(f"- **Google Scholar:** [Profile]({links['scholar']})")
    if links.get("github"):
        lines.append(f"- **GitHub:** @{links['github'].split('/')[-1]} — [{links['github']}]({links['github']})")
    ln = (links.get("linkedin") or "").strip()
    if ln:
        lines.append(f"- **LinkedIn:** [{ln}]({ln})")
    lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(
        "*This README is generated from "
        "[`ankitmathanker.github.io`](https://github.com/ankitmathanker/ankitmathanker.github.io) "
        "via the sync workflow (see `profile.yaml`).*"
    )

    out = "\n".join(lines).rstrip() + "\n"
    return out


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate profile README from profile.yaml")
    parser.add_argument(
        "--output",
        "-o",
        type=Path,
        default=None,
        help="Output path (default: stdout)",
    )
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=None,
        help="Repository root containing profile.yaml (default: parent of scripts/)",
    )
    args = parser.parse_args()

    repo_root = args.repo_root or Path(__file__).resolve().parent.parent
    data = load_profile(repo_root)
    text = render(data)

    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(text, encoding="utf-8", newline="\n")
    else:
        print(text, end="")


if __name__ == "__main__":
    main()
